### ISSUE TITLE
The Lockbox crashes at launch on tablet device

### ISSUE THREAD

**Issue by abodea** [mozilla-lockbox/lockbox-android#192]
## Steps to reproduce
1. Access Google Play Store.
2. Search for Firefox Lockbox.
3. Install the app and open it.
### Expected behavior
The Lockbox for android is correctly opened on the device.
### Actual behavior
The Lockbox for android crashes at launch.
### Device information

* Firefox Lockbox version: 1.0
* Device model:  Google Pixel C (Android 8.0.0) Tablet

### Notes
Note that the crash is with 100% repro.
I was able to reproduce this crash only on tablets, on the other device (Google Pixel XL Android P) the app worked just fine at launch.
For more details please see the attachment: https://goo.gl/Y4jrJf

**Comment by abodea** [comment]
### And here is the Logcat:
1541607849.007 252-5438/? W/StreamHAL: Error from HAL stream in function get_presentation_position: Operation not permitted
1541607849.154 380-433/? W/AppOps: Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
1541607849.731 380-390/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=mozilla.lockbox/.view.RootActivity bnds=[1604,954][1928,1184] (has extras)} from uid 10109
1541607849.747 380-2754/? I/ActivityManager: Start proc 31062:mozilla.lockbox/u0a83 for activity mozilla.lockbox/.view.RootActivity
1541607849.766 180-180/? W/gralloc: Unmapped producer usage 900
1541607849.767 380-433/? W/gralloc: Unmapped producer usage 11
1541607849.767 380-433/? W/gralloc: Unmapped consumer usage 1
1541607849.844 938-30858/? I/PBSessionCacheImpl: Deleted sessionId[12041324506983] from persistence.
1541607849.847 31062-31062/? W/SystemServiceRegistry: No service published for: fingerprint
1541607849.848 31062-31062/? D/AndroidRuntime: Shutting down VM
1541607849.849 31062-31062/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mozilla.lockbox, PID: 31062
    java.lang.RuntimeException: Unable to create application mozilla.lockbox.LockboxApplication: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager
        at mozilla.lockbox.LockboxApplication.onCreate(LockboxApplication.kt:59)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
1541607849.851 380-390/? W/ActivityManager:   Force finishing activity mozilla.lockbox/.view.RootActivity
1541607849.854 938-938/? W/SearchServiceCore: Abort, client detached.
1541607849.855 938-938/? I/StreamController: cleanUpControllerScope(nowcards-15-552131d-1823)
1541607849.855 380-395/? I/ActivityManager: Showing crash dialog for package mozilla.lockbox u0
1541607849.857 938-938/? I/MicroDetector: Keeping mic open: false
1541607849.857 938-29011/? I/DeviceStateChecker: DeviceStateChecker cancelled
1541607849.857 938-30995/? I/MicroRecognitionRunner: Stopping hotword detection.
1541607849.858 938-29018/? I/MicroRecognitionRunner: Detection finished
1541607849.860 938-28979/? I/AudioController: internalShutdown
1541607849.861 938-938/? I/WorkerManager: dispose()
1541607849.865 938-938/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=microdetection::u, WorkerId=microdetection, id=acb5182}
1541607849.875 252-351/? I/SoundTriggerHwService::Module: onCallbackEvent no clients
1541607849.878 938-28979/? I/MicrophoneInputStream: mic_close  SR : 16000 CC : 16 SO : 1999
1541607849.888 938-29011/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::h, WorkerId=context, id=8744001}
1541607849.888 938-29011/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::j, WorkerId=context, id=6c5bea6}
1541607849.888 938-29011/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::k, WorkerId=context, id=cacf0e7}
1541607849.888 938-29011/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::i, WorkerId=context, id=b32494}
1541607849.894 938-29011/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::m, WorkerId=context, id=fe3db3d}
1541607849.906 180-180/? W/gralloc: Unmapped producer usage 900
1541607849.907 380-1087/? D/OpenGLRenderer: Swap behavior 2
1541607849.907 180-180/? W/gralloc: Unmapped producer usage 900
1541607849.907 180-180/? W/gralloc: Unmapped producer usage 900
1541607849.965 180-180/? W/gralloc: Unmapped consumer usage 200
1541607849.965 180-180/? W/gralloc: Unmapped producer usage 900
1541607849.982 180-180/? W/gralloc: Unmapped consumer usage 200
1541607849.982 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.011 563-1745/? I/Places: ?: PlacesBleScanner stop()
1541607850.013 563-563/? I/BeaconBle: ZERO_POWER is disabled.
1541607850.013 563-563/? I/BeaconBle: 'L' hardware scan: scan stopped, no powered clients
1541607850.014 563-563/? I/BeaconBle: Places requested to stop scan
1541607850.014 563-563/? I/BeaconBle: Scan canceled successfully.
1541607850.023 563-1745/? I/PlaceInferenceEngine: [anon] Changed inference mode: 0
1541607850.185 550-550/? D/zz: UtWallpaperService$UtEngine.onVisibilityChanged() false
1541607850.206 550-550/? D/zz: UtRenderer.onNotVisible() 
1541607850.353 380-394/? W/ActivityManager: Activity pause timeout for ActivityRecord{6092a52 u0 mozilla.lockbox/.view.RootActivity t1086 f}
1541607850.360 550-550/? D/zz: UtWallpaperService$UtEngine.onVisibilityChanged() true
1541607850.387 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.390 180-180/? I/chatty: uid=1000(system) allocator@2.0-s identical 1 line
1541607850.393 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.401 180-180/? W/gralloc: Unmapped consumer usage 200
1541607850.401 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.455 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.463 180-180/? W/gralloc: Unmapped consumer usage 200
1541607850.464 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.467 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.470 550-550/? D/zz: UtRenderer.onVisible() 
1541607850.470 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.472 550-550/? W/zz: WeatherManager.doGet() no permissions
1541607850.475 550-550/? W/zz: SunriseUtil.doGet() no permissions
1541607850.489 938-938/? I/SearchServiceCore: Event Bus thread is disabled; marking main thread as EventBus
1541607850.561 180-180/? W/gralloc: Unmapped consumer usage 200
1541607850.561 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.576 938-938/? W/SessionLifecycleManager: Handover failed. Creating new session controller.
1541607850.615 938-938/? I/StreamController: registerScope: nowcards-15-552131d-1823
1541607850.650 938-938/? W/TemplatedStringEvaluato: Got templated string with no display string
1541607850.651 938-938/? I/ClusterController: Found empty cluster, or no children successfully created.
1541607850.679 938-29016/? W/LocationOracle: No location history returned by ContextManager
1541607850.717 180-180/? W/gralloc: Unmapped consumer usage 200
1541607850.717 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.732 938-938/? I/MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
1541607850.735 938-938/? I/AudioController: Created new AudioSource
1541607850.751 938-938/? I/MicroDetectionWorker: onReady
1541607850.751 180-180/? W/gralloc: Unmapped consumer usage 200
1541607850.751 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.764 938-29018/? I/MicroRecognitionRunner: Starting detection.
1541607850.764 938-30858/? I/MicrophoneInputStream: mic_starting  SR : 16000 CC : 16 SO : 1999
1541607850.765 252-31092/? I/AudioFlinger: AudioFlinger's thread 0xea003b00 tid=31092 ready to run
1541607850.769 252-351/? I/SoundTriggerHwService::Module: onCallbackEvent no clients
1541607850.769 938-30858/? I/MicrophoneInputStream: mic_started  SR : 16000 CC : 16 SO : 1999
1541607850.816 938-938/? I/MicroDetectionWorker: onReady
1541607850.821 563-30994/? E/ctxmgr: [ProducerStatusImpl]updateStateForNewContextData: inactive, contextName=7
1541607850.835 563-1745/? I/PlaceInferenceEngine: [anon] Changed inference mode: 0
1541607850.907 180-180/? W/gralloc: Unmapped consumer usage 200
1541607850.907 180-180/? W/gralloc: Unmapped producer usage 900
1541607850.914 997-1114/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
1541607850.982 563-1745/? I/Places: ?: PlacesBleScanner start() with priority 2
1541607850.982 563-1745/? I/PlaceInferenceEngine: [anon] Changed inference mode: 1
1541607850.999 563-1745/? I/Places: Converted 0 out of 10 WiFi scans
1541607851.024 563-563/? I/BeaconBle: Client requested scan, settings=BleSettings [scanMode=ZERO_POWER, callbackType=ALL_MATCHES, reportDelayMillis=0, 1 filters, 0 clients, callingClientName=Places]
1541607851.035 563-1745/? I/PlaceInferenceEngine: [anon] Changed inference mode: 1
1541607851.049 563-580/? I/zygote64: Background concurrent copying GC freed 151848(6MB) AllocSpace objects, 42(2MB) LOS objects, 49% free, 14MB/29MB, paused 148us total 189.318ms
1541607851.056 563-563/? I/BeaconBle: ZERO_POWER is disabled.
1541607851.056 563-563/? I/BeaconBle: 'L' hardware scan: scan stopped, no powered clients
1541607851.072 938-948/? I/zygote64: Background concurrent copying GC freed 337488(12MB) AllocSpace objects, 17(5MB) LOS objects, 49% free, 17MB/34MB, paused 195us total 154.142ms
1541607851.076 563-31086/? I/PlaceInferenceEngine: No beacon scan available - ignoring candidates.
1541607851.144 380-389/? I/zygote64: Background concurrent copying GC freed 26460(1702KB) AllocSpace objects, 2(40KB) LOS objects, 42% free, 17MB/30MB, paused 391us total 110.358ms
1541607851.146 180-180/? W/gralloc: Unmapped consumer usage 200
1541607851.146 180-180/? W/gralloc: Unmapped producer usage 900
1541607855.256 380-390/? W/ActivityManager:   Force finishing activity mozilla.lockbox/.view.RootActivity
1541607855.256 380-390/? I/ActivityManager: Killing 31062:mozilla.lockbox/u0a83 (adj 900): crash
1541607855.298 252-5438/? I/audio_cras_dsp: pipeline created
1541607855.298 252-5438/? D//system/bin/audioserver: instantiate source
1541607855.298 252-5438/? D//system/bin/audioserver: instantiate drc
1541607855.298 252-5438/? D//system/bin/audioserver: instantiate eq2
1541607855.298 252-5438/? D//system/bin/audioserver: instantiate sink
1541607855.298 252-5438/? D//system/bin/audioserver: connect audio buf 0 to output_source:0 (out)
1541607855.298 252-5438/? D//system/bin/audioserver: connect audio buf 1 to output_source:1 (out)
1541607855.298 252-5438/? D//system/bin/audioserver: connect audio buf 0 to drc:0 (in)
1541607855.298 252-5438/? D//system/bin/audioserver: connect audio buf 1 to drc:1 (in)
1541607855.298 252-5438/? D//system/bin/audioserver: connect audio buf 0 to drc:2 (out)
1541607855.299 252-5438/? D//system/bin/audioserver: connect audio buf 1 to drc:3 (out)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=1) to drc:4 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=0) to drc:5 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=1) to drc:6 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=-36) to drc:7 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=18) to drc:8 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=20) to drc:9 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=0.003) to drc:10 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=0.2) to drc:11 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=3) to drc:12 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=450) to drc:13 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=1) to drc:14 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=-33) to drc:15 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=20) to drc:16 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=23) to drc:17 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=0.003) to drc:18 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=0.2) to drc:19 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=6) to drc:20 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=2200) to drc:21 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=1) to drc:22 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=-18) to drc:23 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=20) to drc:24 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=6) to drc:25 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=0.003) to drc:26 (in)
1541607855.299 252-5438/? D//system/bin/audioserver: connect control (val=0.2) to drc:27 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=-1) to drc:28 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect audio buf 0 to eq2:0 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect audio buf 1 to eq2:1 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect audio buf 0 to eq2:2 (out)
1541607855.300 252-5438/? D//system/bin/audioserver: connect audio buf 1 to eq2:3 (out)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=2) to eq2:4 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=330) to eq2:5 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=0) to eq2:6 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=0) to eq2:7 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=2) to eq2:8 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=330) to eq2:9 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=0) to eq2:10 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=0) to eq2:11 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:12 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=550) to eq2:13 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=3) to eq2:14 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=-10) to eq2:15 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:16 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=550) to eq2:17 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=3) to eq2:18 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=-10) to eq2:19 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:20 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=740) to eq2:21 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=3) to eq2:22 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=-8) to eq2:23 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:24 (in)
1541607855.300 252-5438/? D//system/bin/audioserver: connect control (val=750) to eq2:25 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=3) to eq2:26 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=-6) to eq2:27 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:28 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=1000) to eq2:29 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=3) to eq2:30 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=-3) to eq2:31 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:32 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=360) to eq2:33 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=2) to eq2:34 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=-4) to eq2:35 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:36 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=1300) to eq2:37 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=3) to eq2:38 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=-4) to eq2:39 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:40 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=1000) to eq2:41 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=2) to eq2:42 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=-4) to eq2:43 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:44 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=360) to eq2:45 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=1) to eq2:46 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=-3) to eq2:47 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:48 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=1200) to eq2:49 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=2) to eq2:50 (in)
1541607855.301 252-5438/? D//system/bin/audioserver: connect control (val=-5) to eq2:51 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:52 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=2200) to eq2:53 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=7) to eq2:54 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=-9) to eq2:55 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=6) to eq2:56 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=2200) to eq2:57 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=7) to eq2:58 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=-9) to eq2:59 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=5) to eq2:60 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=6000) to eq2:61 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=0) to eq2:62 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=-2) to eq2:63 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=5) to eq2:64 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=6000) to eq2:65 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=1) to eq2:66 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect control (val=-2) to eq2:67 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect audio buf 0 to output_sink:0 (in)
1541607855.302 252-5438/? D//system/bin/audioserver: connect audio buf 1 to output_sink:1 (in)
1541607855.309 252-5438/? W/StreamHAL: Error from HAL stream in function get_presentation_position: Operation not permitted
1541607855.455 380-433/? W/AppOps: Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
1541607855.664 938-28987/? I/EventLogSendingHelper: Sending log events.
1541607857.239 380-799/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=mozilla.lockbox/.view.RootActivity bnds=[1604,954][1928,1184] (has extras)} from uid 10109
1541607857.255 380-2843/? I/ActivityManager: Start proc 31095:mozilla.lockbox/u0a83 for activity mozilla.lockbox/.view.RootActivity
1541607857.280 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.282 380-433/? W/gralloc: Unmapped producer usage 11
1541607857.282 380-433/? W/gralloc: Unmapped consumer usage 1
1541607857.357 938-29477/? I/PBSessionCacheImpl: Deleted sessionId[12041324507306] from persistence.
1541607857.367 31095-31095/? W/SystemServiceRegistry: No service published for: fingerprint
1541607857.368 31095-31095/? D/AndroidRuntime: Shutting down VM
1541607857.369 938-938/? W/SearchServiceCore: Abort, client detached.
1541607857.370 938-938/? I/StreamController: cleanUpControllerScope(nowcards-15-552131d-1823)
1541607857.371 31095-31095/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mozilla.lockbox, PID: 31095
    java.lang.RuntimeException: Unable to create application mozilla.lockbox.LockboxApplication: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager
        at mozilla.lockbox.LockboxApplication.onCreate(LockboxApplication.kt:59)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
1541607857.372 938-938/? I/MicroDetector: Keeping mic open: false
1541607857.372 380-803/? W/ActivityManager:   Force finishing activity mozilla.lockbox/.view.RootActivity
1541607857.373 938-29016/? I/DeviceStateChecker: DeviceStateChecker cancelled
1541607857.374 938-31089/? I/MicroRecognitionRunner: Stopping hotword detection.
1541607857.374 938-29018/? I/MicroRecognitionRunner: Detection finished
1541607857.374 938-29477/? I/AudioController: internalShutdown
1541607857.377 380-395/? I/ActivityManager: Showing crash dialog for package mozilla.lockbox u0
1541607857.378 184-184/? D/SurfaceFlinger: Backpressure trigger, skipping transaction & refresh!
1541607857.391 252-351/? I/SoundTriggerHwService::Module: onCallbackEvent no clients
1541607857.393 938-29477/? I/MicrophoneInputStream: mic_close  SR : 16000 CC : 16 SO : 1999
1541607857.411 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.411 380-1087/? I/OpenGLRenderer: Initialized EGL, version 1.4
1541607857.411 380-1087/? D/OpenGLRenderer: Swap behavior 2
1541607857.411 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.411 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.454 180-180/? W/gralloc: Unmapped consumer usage 200
1541607857.454 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.469 180-180/? W/gralloc: Unmapped consumer usage 200
1541607857.469 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.530 1021-1037/? I/zygote64: Background concurrent copying GC freed 87528(4MB) AllocSpace objects, 65(3MB) LOS objects, 49% free, 14MB/28MB, paused 185us total 122.357ms
1541607857.704 550-550/? D/zz: UtWallpaperService$UtEngine.onVisibilityChanged() false
1541607857.724 550-550/? D/zz: UtRenderer.onNotVisible() 
1541607857.874 380-394/? W/ActivityManager: Activity pause timeout for ActivityRecord{be41fa0 u0 mozilla.lockbox/.view.RootActivity t1087 f}
1541607857.880 550-550/? D/zz: UtWallpaperService$UtEngine.onVisibilityChanged() true
1541607857.921 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.938 180-180/? I/chatty: uid=1000(system) allocator@2.0-s identical 3 lines
1541607857.944 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.948 180-180/? W/gralloc: Unmapped consumer usage 200
1541607857.948 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.951 180-180/? W/gralloc: Unmapped producer usage 900
1541607857.990 550-550/? D/zz: UtRenderer.onVisible() 
1541607857.992 550-550/? W/zz: WeatherManager.doGet() no permissions
1541607857.993 550-550/? W/zz: SunriseUtil.doGet() no permissions
1541607858.013 180-180/? W/gralloc: Unmapped consumer usage 200
1541607858.013 180-180/? W/gralloc: Unmapped producer usage 900
1541607858.032 938-938/? W/SessionLifecycleManager: Handover failed. Creating new session controller.
1541607858.070 938-938/? I/StreamController: registerScope: nowcards-15-552131d-1823
1541607858.101 938-938/? W/TemplatedStringEvaluato: Got templated string with no display string
1541607858.101 938-938/? I/ClusterController: Found empty cluster, or no children successfully created.
1541607858.130 938-938/? I/MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
1541607858.130 180-180/? W/gralloc: Unmapped consumer usage 200
1541607858.130 180-180/? W/gralloc: Unmapped producer usage 900
1541607858.132 938-938/? I/AudioController: Created new AudioSource
1541607858.134 938-938/? I/MicroDetectionWorker: onReady
1541607858.147 180-180/? W/gralloc: Unmapped consumer usage 200
1541607858.147 180-180/? W/gralloc: Unmapped producer usage 900
1541607858.167 938-28983/? I/MicroRecognitionRunner: Starting detection.
1541607858.168 938-28979/? I/MicrophoneInputStream: mic_starting  SR : 16000 CC : 16 SO : 1999
1541607858.169 252-31119/? I/AudioFlinger: AudioFlinger's thread 0xe9f832c0 tid=31119 ready to run
1541607858.173 252-351/? I/SoundTriggerHwService::Module: onCallbackEvent no clients
1541607858.179 938-28979/? I/MicrophoneInputStream: mic_started  SR : 16000 CC : 16 SO : 1999
1541607858.226 938-938/? I/MicroDetectionWorker: onReady
1541607858.450 180-180/? W/gralloc: Unmapped consumer usage 200
1541607858.450 180-180/? W/gralloc: Unmapped producer usage 900
1541607858.464 997-1114/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
1541607860.665 938-29018/? I/EventLogSendingHelper: Sending log events.
