### ISSUE TITLE
[Crash] TypeCastException in FingerprintManager

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#207]
Reported in Play Store pre-launch checklist tests on 
Xperia XZ1 Compact with Android 8.0:

>Issue: java.lang.RuntimeException: Unable to create application mozilla.lockbox.LockboxApplication: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager

```
FATAL EXCEPTION: main
Process: mozilla.lockbox, PID: 13148
java.lang.RuntimeException: Unable to create application mozilla.lockbox.LockboxApplication: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5825)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:251)
	at android.app.ActivityThread.main(ActivityThread.java:6572)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager
	at mozilla.lockbox.LockboxApplication.onCreate(LockboxApplication.kt:59)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5822)
	... 8 more
```

_Originally posted by @devinreams in https://github.com/mozilla-lockbox/lockbox-android/issues/194#issuecomment-437963871_

**Comment by jmedveckyh** [comment]
The bug is still present in the latest release (Release candidate).

Crash happens because a null can be returned in context.getSystemService(Context.FINGERPRINT_SERVICE) (line 78 in FingerprintStore.kt) in devices which dont have fingerprint sensor.

I was able to get the application running on nexus 4 which doesnt have fingerprint sensor after modifying these lines but i dont want to create a pull request because i never wrote a single program in Kotlin and im sure this can be solved in a much more elegant way.

![fixes](https://user-images.githubusercontent.com/5638498/54707209-df6d8e80-4b40-11e9-99b6-593d35bb2679.PNG)

Cheers
