### ISSUE TITLE
Background and open app before autolock causes crash on API 27

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#308]
Follow up to #240 

I think I get a crash on Pixel, API 27 when I try to re-open the app immediately after backgrounding it, before the autolock time (eg: in less than 1 minute). But not when hard quitting. 🙃  

Steps for backgrounding crash:

- open app
- set autolock timer setting to 1 minute
- return the list view
- tap 'home' button to background
- tap app to re-open app
- crash! ("Reopen app again" shown in dialog)

Expected: opens to unlocked list view
Actual: shows crash dialog and re-open shows locked screen

```
2018-12-19 11:20:32.828 885-8010/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=mozilla.lockbox/.view.RootActivity bnds=[641,252][843,514]} from uid 10036
2018-12-19 11:20:32.830 673-673/? D/QCOM PowerHAL: LAUNCH HINT: ON
2018-12-19 11:20:32.838 673-673/? D/QCOM PowerHAL: Activity launch hint handled
2018-12-19 11:20:32.854 656-1969/? I/ACDB-LOADER: ACDB AFE returned = -19
2018-12-19 11:20:32.854 656-1969/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
2018-12-19 11:20:32.854 656-1969/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
2018-12-19 11:20:32.854 656-1969/? D/audio_route: Apply path: speaker
2018-12-19 11:20:32.854 656-1969/? D/audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
2018-12-19 11:20:32.854 656-1969/? D/audio_route: Apply path: low-latency-playback speaker
2018-12-19 11:20:32.854 1943-1945/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
2018-12-19 11:20:32.854 1943-1945/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
2018-12-19 11:20:32.886 656-1969/? D/audio_hw_primary: out_write: retry previous failed cal level set
2018-12-19 11:20:32.917 8452-8517/mozilla.lockbox V/libloginsapi_ffi: event Readable Token(4194303)
2018-12-19 11:20:32.917 8452-8517/mozilla.lockbox D/libloginsapi_ffi: loop process - 1 events, 0.000s
2018-12-19 11:20:32.918 8452-8517/mozilla.lockbox V/libloginsapi_ffi: deregistering handle with poller
2018-12-19 11:20:32.918 8452-8517/mozilla.lockbox D/libloginsapi_ffi: dropping I/O source: 1
2018-12-19 11:20:32.924 8452-8517/mozilla.lockbox V/libloginsapi_ffi: signal: Closed
2018-12-19 11:20:32.951 656-29671/? D/sound_trigger_hw: stdev_stop_recognition:[2] Enter
2018-12-19 11:20:32.951 656-29671/? D/sound_trigger_hw: dereg_hal_event_session: ST_EVENT_SESSION_DEREGISTER capture_handle 62 pcm 0xf5ab21c0
2018-12-19 11:20:32.951 656-29671/? I/sound_trigger_hw: cpe_stop:[2] Enter
2018-12-19 11:20:32.958 1424-1439/? W/asset: Asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:32.958 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk
2018-12-19 11:20:32.958 1424-1439/? W/PackageManager: Failure retrieving resources for com.android.chrome
2018-12-19 11:20:32.958 1424-1439/? W/asset: Asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:32.958 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk
2018-12-19 11:20:32.958 1424-1439/? W/PackageManager: Failure retrieving resources for com.android.chrome
2018-12-19 11:20:32.959 1424-1439/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:32.959 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:32.959 1424-1439/? W/PackageManager: Failure retrieving resources for com.google.android.gm
2018-12-19 11:20:32.959 1424-1439/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:32.959 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:32.959 1424-1439/? W/PackageManager: Failure retrieving resources for com.google.android.gm
2018-12-19 11:20:32.959 1424-1439/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:32.959 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:32.959 1424-1439/? W/PackageManager: Failure retrieving resources for com.google.android.gm
2018-12-19 11:20:32.968 656-29671/? D/sound_trigger_hw: cpe_stop:[2] Exit, status=0
2018-12-19 11:20:32.968 656-29671/? D/sound_trigger_hw: sound_trigger_set_device: disable device (1) = listen-cpe-handset-mic
2018-12-19 11:20:32.973 656-29671/? D/sound_trigger_hw: cpe_dereg_sm_params:[2] Enter
2018-12-19 11:20:32.973 656-29671/? D/sound_trigger_hw: stdev_stop_recognition:[2] Exit status 0
2018-12-19 11:20:32.974 9895-9895/? I/GsaVoiceInteractionSrv: Stop Hotword Recognition status: true
2018-12-19 11:20:33.032 8452-8457/mozilla.lockbox I/zygote64: Do partial code cache collection, code=249KB, data=163KB
2018-12-19 11:20:33.032 8452-8457/mozilla.lockbox I/zygote64: After code cache collection, code=249KB, data=163KB
2018-12-19 11:20:33.032 8452-8457/mozilla.lockbox I/zygote64: Increasing code cache capacity to 1024KB
2018-12-19 11:20:33.053 8452-8452/mozilla.lockbox W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | navView.menuHeader must not be null
2018-12-19 11:20:33.053 8452-8452/mozilla.lockbox W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
2018-12-19 11:20:33.053 8452-8452/mozilla.lockbox W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
2018-12-19 11:20:33.053 8452-8452/mozilla.lockbox W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
2018-12-19 11:20:33.053 8452-8452/mozilla.lockbox W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at android.os.Looper.loop(Looper.java:164)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-12-19 11:20:33.054 8452-8452/mozilla.lockbox W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2018-12-19 11:20:33.055 8452-8452/mozilla.lockbox W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2018-12-19 11:20:33.055 8452-8452/mozilla.lockbox W/System.err: Caused by: java.lang.IllegalStateException: navView.menuHeader must not be null
2018-12-19 11:20:33.055 8452-8452/mozilla.lockbox W/System.err:     at mozilla.lockbox.view.ItemListFragment.updateAccountProfile(ItemListFragment.kt:179)
2018-12-19 11:20:33.055 8452-8452/mozilla.lockbox W/System.err:     at mozilla.lockbox.presenter.ItemListPresenter$onViewReady$14.invoke(ItemListPresenter.kt:128)
2018-12-19 11:20:33.055 8452-8452/mozilla.lockbox W/System.err:     at mozilla.lockbox.presenter.ItemListPresenter$onViewReady$14.invoke(ItemListPresenter.kt:46)
2018-12-19 11:20:33.055 8452-8452/mozilla.lockbox W/System.err:     at mozilla.lockbox.presenter.ItemListPresenter$sam$io_reactivex_functions_Consumer$0.accept(Unknown Source:21)
2018-12-19 11:20:33.055 8452-8452/mozilla.lockbox W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
2018-12-19 11:20:33.055 8452-8452/mozilla.lockbox W/System.err: 	... 10 more
2018-12-19 11:20:33.064 8452-8452/mozilla.lockbox D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
2018-12-19 11:20:33.188 885-2129/? W/ActivityManager:   Force finishing activity mozilla.lockbox/.view.RootActivity
2018-12-19 11:20:33.192 885-915/? I/ActivityManager: Showing crash dialog for package mozilla.lockbox u0
2018-12-19 11:20:33.197 885-914/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2018-12-19 11:20:33.198 885-914/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2018-12-19 11:20:33.265 27379-27379/? D/zz: UtWallpaperService$UtEngine.onVisibilityChanged() false
2018-12-19 11:20:33.268 27379-27379/? D/zz: UtRenderer.onNotVisible() 
2018-12-19 11:20:33.333 1424-1439/? W/asset: Asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.333 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk
2018-12-19 11:20:33.333 1424-1439/? W/PackageManager: Failure retrieving resources for com.android.chrome
2018-12-19 11:20:33.333 1424-1439/? W/asset: Asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.333 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk
2018-12-19 11:20:33.333 1424-1439/? W/PackageManager: Failure retrieving resources for com.android.chrome
2018-12-19 11:20:33.334 1424-1439/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.334 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:33.334 1424-1439/? W/PackageManager: Failure retrieving resources for com.google.android.gm
2018-12-19 11:20:33.334 1424-1439/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.334 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:33.334 1424-1439/? W/PackageManager: Failure retrieving resources for com.google.android.gm
2018-12-19 11:20:33.334 1424-1439/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.334 1424-1439/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:33.334 1424-1439/? W/PackageManager: Failure retrieving resources for com.google.android.gm

2018-12-19 11:20:33.690 885-914/? W/ActivityManager: Activity pause timeout for ActivityRecord{ec9def3 u0 mozilla.lockbox/.view.RootActivity t460 f}
2018-12-19 11:20:33.703 27379-27379/? D/zz: UtWallpaperService$UtEngine.onVisibilityChanged() true
2018-12-19 11:20:33.708 27379-27379/? D/zz: UtRenderer.onVisible() 
2018-12-19 11:20:33.709 27379-27379/? V/zz: WeatherManager.doGet() getting weather from Awareness
2018-12-19 11:20:33.715 27379-27379/? V/zz: SunriseUtil.doGet() getting location from Awareness
2018-12-19 11:20:33.807 673-673/? D/QCOM PowerHAL: LAUNCH HINT: OFF
2018-12-19 11:20:33.820 1424-22270/? W/asset: Asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.820 1424-22270/? E/ResourcesManager: failed to add asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk
2018-12-19 11:20:33.820 1424-22270/? W/PackageManager: Failure retrieving resources for com.android.chrome
2018-12-19 11:20:33.820 1424-22270/? W/asset: Asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.820 1424-22270/? E/ResourcesManager: failed to add asset path /data/app/com.android.chrome-udJNGUCvHfMjG40Li1E3Ng==/base.apk
2018-12-19 11:20:33.820 1424-22270/? W/PackageManager: Failure retrieving resources for com.android.chrome
2018-12-19 11:20:33.820 1424-22270/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.820 1424-22270/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:33.820 1424-22270/? W/PackageManager: Failure retrieving resources for com.google.android.gm
2018-12-19 11:20:33.820 1424-22270/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.820 1424-22270/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:33.820 1424-22270/? W/PackageManager: Failure retrieving resources for com.google.android.gm
2018-12-19 11:20:33.820 1424-22270/? W/asset: Asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk is neither a directory nor file (type=1).
2018-12-19 11:20:33.820 1424-22270/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.gm-ybRSU7xJeZj03JXrd6hgEQ==/base.apk
2018-12-19 11:20:33.821 1424-22270/? W/PackageManager: Failure retrieving resources for com.google.android.gm
2018-12-19 11:20:33.845 656-29671/? D/sound_trigger_hw: stdev_start_recognition:[2] Enter
2018-12-19 11:20:33.846 656-29671/? D/sound_trigger_platform: platform_stdev_is_session_allowed: stdev->audio_concurrency_active 0 session_allowed 1
2018-12-19 11:20:33.846 656-29671/? D/sound_trigger_hw: get_confidence_levels_payload: No smlib for uuid, sending opaque data
2018-12-19 11:20:33.846 656-29671/? D/sound_trigger_platform: platform_stdev_send_hwmad_cal: previous acdb_id 128 new acdb_id 128, sw_mad 0 return
2018-12-19 11:20:33.846 656-29671/? D/sound_trigger_platform: platform_stdev_send_calibration: sending afe calibration for device(1) acdb_id(128)
2018-12-19 11:20:33.846 656-29671/? I/ACDB-LOADER: ACDB AFE returned = -19
2018-12-19 11:20:33.846 656-29671/? D/sound_trigger_hw: sound_trigger_set_device: enable device (1) = listen-cpe-handset-mic
2018-12-19 11:20:33.846 656-29671/? D/audio_route: Apply path: listen-cpe-handset-mic
2018-12-19 11:20:33.866 656-29671/? D/sound_trigger_hw: cpe_reg_sm_params:[2] Enter
2018-12-19 11:20:33.866 656-29671/? D/sound_trigger_hw: configure_lab: media_cfg format=0, packing=1, events=0, mode=1
2018-12-19 11:20:33.872 27379-27379/? V/zz: WeatherManager$3.onResult() successful result: [WeatherVo] conditions: CLEAR (1)
2018-12-19 11:20:33.873 27379-27379/? V/zz: TimelapseRenderer.updateWeatherCondition() CLEAR
2018-12-19 11:20:33.891 27379-27379/? V/zz: SunriseUtil$3.onResult() location: 39.757557, -105.00685
2018-12-19 11:20:33.891 27379-27379/? V/zz: AbstractSunriseUtil.getSunriseSunset() sunrise : Wed Dec 19 07:17:47 MST 2018
2018-12-19 11:20:33.891 27379-27379/? V/zz: AbstractSunriseUtil.getSunriseSunset() sunset  : Wed Dec 19 16:43:04 MST 2018
2018-12-19 11:20:33.891 27379-27379/? V/zz: SunriseUtil$3.onResult() sunrise/sunset: 0.30401656, 0.696585
2018-12-19 11:20:33.892 27379-27379/? V/zz: TimelapseRenderer$1.onReceive() got sunrise broadcast - true
2018-12-19 11:20:33.904 656-29671/? D/sound_trigger_hw: cpe_reg_sm_params:[2] Exit, status=0
2018-12-19 11:20:33.904 656-29671/? D/sound_trigger_hw: reg_hal_event_session: ST_EVENT_SESSION_REGISTER capture_handle 62 pcm 0xf5ab21c0
2018-12-19 11:20:33.904 656-29671/? D/sound_trigger_hw: cpe_start:[2] Enter
2018-12-19 11:20:33.905 2032-2361/? I/GeofencerStateMachine: addGeofences called by com.google.android.gms
2018-12-19 11:20:33.908 656-29671/? D/sound_trigger_hw: cpe_start:[2] Exit, status=0
2018-12-19 11:20:33.908 656-29671/? D/sound_trigger_hw: stdev_start_recognition:[2] Exit status 0
2018-12-19 11:20:33.909 885-8010/? I/SoundTriggerHelper: startRecognition successful.
2018-12-19 11:20:33.909 9895-9895/? I/GsaVoiceInteractionSrv: Start Hotword Recognition Status: true
2018-12-19 11:20:33.907 2032-2725/? I/GeofencerStateMachine: Use last location to update newly added Geofences.
2018-12-19 11:20:33.967 2032-2361/? I/GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_IDS Ids=[7ee6825c-0d57-4f4c-bfd6-aebf39590a9c], packageName=com.google.android.gms]

2018-12-19 11:20:34.054 2032-2043/? I/zygote64: Background concurrent copying GC freed 266429(12MB) AllocSpace objects, 46(2MB) LOS objects, 49% free, 14MB/29MB, paused 168us total 129.228ms



2018-12-19 11:20:34.310 12631-12677/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...





2018-12-19 11:20:35.298 32225-7149/? I/EventLogSendingHelper: Sending log events.
2018-12-19 11:20:35.337 32225-7154/? I/EventLogSendingHelper: Sending log events.
2018-12-19 11:20:36.100 656-29671/? D/audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
2018-12-19 11:20:36.110 656-29671/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
2018-12-19 11:20:36.110 656-29671/? D/audio_hw_primary: disable_snd_device: snd_device(2: speaker)
2018-12-19 11:20:36.463 885-30886/? D/DhcpClient: Received packet: 6c:e8:5c:e4:67:a6 ACK: your new IP /10.6.22.253, netmask /255.255.240.0, gateways [/10.6.16.1] DNS servers: /8.8.8.8 /8.8.4.4 , lease time 86400

```

**Comment by devinreams** [comment]
I'm not getting this any more (close, reopen, no crash).

But after 1 minute in the background and re-opening, I do not get a prompt to unlock as seen at #260 

Closing this one as fixed/no longer reproducible. 🤘
