### ISSUE TITLE
ViewNode crash: className must not be null on Android Q

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-lockbox/lockbox-android#530]
Lockbox crashes a lot, always with the following exception:

```
2019-03-22 22:13:25.412 21339-21339/mozilla.lockbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mozilla.lockbox, PID: 21339
    java.lang.IllegalStateException: className must not be null
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpNode(ViewNode+.kt:18)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpChildren(ViewNode+.kt:62)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpNode(ViewNode+.kt:46)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpChildren(ViewNode+.kt:62)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpNode(ViewNode+.kt:46)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpChildren(ViewNode+.kt:62)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpNode(ViewNode+.kt:46)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpChildren(ViewNode+.kt:62)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpNode(ViewNode+.kt:46)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpChildren(ViewNode+.kt:62)
        at mozilla.lockbox.extensions.ViewNode_Kt.dumpNode(ViewNode+.kt:46)
        at mozilla.lockbox.extensions.ViewNode_Kt.dump(ViewNode+.kt:10)
        at mozilla.lockbox.LockboxAutofillService.onFillRequest(LockboxAutofillService.kt:71)
        at android.service.autofill.AutofillService.lambda$-android_service_autofill_AutofillService_15826(AutofillService.java:320)
        at android.service.autofill.-$Lambda$svbjmB3NFhHnuZrn67G14PFSJlY.$m$0(Unknown Source:4)
        at android.service.autofill.-$Lambda$svbjmB3NFhHnuZrn67G14PFSJlY.executeMessage(Unknown Source:0)
        at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6950)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
```

The following STR reproduce the crash in 100% for me:

1. make sure Lockbox is enabled in Android autofill options
2. long press to homescreen to add an app icon to the home screen
3. try to enter an app name in the search field

=> Lockbox crashes

### Device information

* Android device: HTC U11 / Android 8.0
* Lockbox version: revision c1f7d1ab474b5312228500bdf612be6aab5273b4

**Comment by cadeyrn** [comment]
Other STR are (also crashes in 100% for me):

1. open the Facebook app
2. go to your notifications
3. click on a notifaction that someone marked you in a comment

=> Lockbox crashes with same exception as above.

**Comment by devinreams** [comment]
We'll prioritize and see since this has some steps to reproduce. Thanks @cadeyrn

**Comment by devinreams** [comment]
Confirmed still and more detail in Sentry:
https://sentry.prod.mozaws.net/operations/lockbox-android/issues/5550830/?query=is:unresolved

**Comment by devinreams** [comment]
Sentry issue: [LOCKBOX-ANDROID-N](https://sentry.prod.mozaws.net/operations/lockbox-android/issues/5550830/)
