### ISSUE TITLE
ActivityNotFoundException in REQUEST_SET_AUTOFILL_SERVICE

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockbox/lockbox-android#638]
https://sentry.prod.mozaws.net/operations/lockbox-android/issues/5637379/

```
ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.REQUEST_SET_AUTOFILL_SERVICE dat=package:com.mozilla.lockbox }
    at mozilla.lockbox.presenter.RoutePresenter.openSetting(RoutePresenter.kt:112)
    at mozilla.lockbox.presenter.AppRoutePresenter.route(AppRoutePresenter.kt:90)
    at mozilla.lockbox.presenter.AppRoutePresenter$onResume$1.invoke(AppRoutePresenter.kt:55)
    at mozilla.lockbox.presenter.AppRoutePresenter$onResume$1.invoke(AppRoutePresenter.kt:33)
    at mozilla.lockbox.presenter.AppRoutePresenter$sam$io_reactivex_functions_Consumer$0.accept
...
(18 additional frame(s) were not displayed)

OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | No Activity found to handle Intent { act=android.settings.REQUEST_SET_AUTOFILL_SERVICE dat=package:com.mozilla.lockbox }
    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
    at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
...
(9 additional frame(s) were not displayed)

The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | No Activity found to handle Intent { act=android.settings.REQUEST_SET_AUTOFILL_SERVICE dat=package:com.mozilla.lockbox }
```

**Comment by eliserichards** [comment]
Needs reproduce. Could still be happening, but it's hard to tell because of the sentry dobfuscation problems (#827).
